function linea = getplotdata(varargin)
% a utility function to extact data from open charts (especially ones
% generated by AARAE).

% This still needs work

hasfunname = find(strcmp(varargin,'funname'));
if ~isempty(hasfunname), funname = varargin{hasfunname+1}; end

hasinputname = find(strcmp(varargin,'inputname'));
if ~isempty(hasinputname), inputname = varargin{hasinputname+1}; end



if nargin > 0
    
    % let's check all of the open figures
    h = findobj('type','figure',...
        '-not','tag','aarae',...
        '-not','tag','AARAE table');
    hvalid = false(length(h),1);
    if exist('inputname','var') && exist('funname','var')
        for i = 1:length(h)
            UserData = get(h(i),'UserData');
            [r,c] = size(UserData);
            if r>=4 && c >=2
                if strcmp(UserData{1,2},'AARAE')
                    
                end
            end
        end
        
    end
    
    ok = false(length(h),1);
    hvalidindex = 0;
    for i = 1:length(h)
        Figtag = get(h(i),'Tag');
        if ~strcmp(Figtag,'AARAE table')
            ok(i) = true;
            UserData = get(h(i),'UserData');
            [r,c] = size(UserData);
            if r>=4 && c >=2
                if ~strcmp(UserData{1,2},'AARAE')
                    ok(i) = false;
                else
                    funname = Userdata{2,2};
                    input = Userdata{3,2};
                    
                    hvalidindex = hvalidindex+1;
                    chartstring{hvalidindex} = [funname ' ' input];
                    okcharts(hvalidindex) = i;
                end
            end
        end
    end
    h = h(hvalidindex);
    
    % dialog box to choose?
    
    

    
    
else
    children = get(gca,'Children');
    for i = 1:length(children)
        linea.data{i,1} = get(children(i));
    end
    linea.axisproperties = get(gca);
    linea.axisproperties.xlabel = get(get(gca,'XLabel'),'String');
    linea.axisproperties.ylabel = get(get(gca,'YLabel'),'String');
    linea.axisproperties.zlabel = get(get(gca,'ZLabel'),'String');
    %linea.axisproperties.xscale = get(gca,'XScale');
    %linea.axisproperties.yscale = get(gca,'YScale');
    %linea.axisproperties.zscale = get(gca,'ZScale');
    
end
end